CREATE TABLE USERS(
	CHATID				INT				NOT NULL,
	LANGUAGE			CHAR(2)					,
	SHOW_BITRATE		BOOLEAN					,
	SHOW_HEARTS			BOOLEAN					,
	SHOW_AUDIO_FORMAT	BOOLEAN					,
	RESULTS_COUNT		INT						,
	LAST_LIST			TEXT					,
	LAST_PAGE			INT						,
	LAST_URLS_PAGE		INT						,
	URLS				TEXT					,
	WITHOUT_FORMATING	TEXT					,
	HEARTS_BUTTONS		BOOLEAN					,
	PLAYLIST_PAGE		INT						,
	LAST_URLS_LIST		TEXT					,
	PRIMARY KEY (CHATID)

);

CREATE TABLE FAVOURITES(
	KEY_ID				INT		  AUTO_INCREMENT,
	CHATID				INT				NOT NULL,
	NAME				TEXT					,
	FILE_ID				TEXT
	PRIMARY KEY (KEY_ID)
);

